//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenIDE.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenIDE.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ASPX {
            get {
                object obj = ResourceManager.GetObject("ASPX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BAT_Mode {
            get {
                object obj = ResourceManager.GetObject("BAT_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Boo {
            get {
                object obj = ResourceManager.GetObject("Boo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Cg_Mode {
            get {
                object obj = ResourceManager.GetObject("Cg_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Coco_Mode {
            get {
                object obj = ResourceManager.GetObject("Coco_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CPP_Mode {
            get {
                object obj = ResourceManager.GetObject("CPP_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CSharp_Mode {
            get {
                object obj = ResourceManager.GetObject("CSharp_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HLSL_Mode {
            get {
                object obj = ResourceManager.GetObject("HLSL_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HTML_Mode {
            get {
                object obj = ResourceManager.GetObject("HTML_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Java_Mode {
            get {
                object obj = ResourceManager.GetObject("Java_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] JavaScript_Mode {
            get {
                object obj = ResourceManager.GetObject("JavaScript_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; &gt;
        ///	&lt;xsd:annotation&gt;
        ///		&lt;xsd:documentation&gt;
        ///		This schema defines the syntax for mode definitions in SharpDevelop.
        ///		The schema can be simplified quite a bit but it does the job as is.
        ///		
        ///		
        ///		If you are using this file as a reference it is probably easiest to scroll to
        ///		the botton to find the definition of the root element called SyntaxDefinition and
        ///		then unwind the different type definitions and ref [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Patch_Mode {
            get {
                object obj = ResourceManager.GetObject("Patch_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHP_Mode {
            get {
                object obj = ResourceManager.GetObject("PHP_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SQL_Mode {
            get {
                object obj = ResourceManager.GetObject("SQL_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxModes version=&quot;1.0&quot;&gt;
        ///	&lt;Mode file       = &quot;ASPX.xshd&quot;
        ///	      name       = &quot;ASP/XHTML&quot;
        ///	      extensions = &quot;.asp;.aspx;.asax;.asmx&quot;/&gt;
        ///	
        ///	&lt;Mode file       = &quot;BAT-Mode.xshd&quot;
        ///	      name       = &quot;BAT&quot;
        ///	      extensions = &quot;.bat&quot;/&gt;
        ///	
        ///	&lt;Mode file       = &quot;Boo.xshd&quot;
        ///	      name       = &quot;Boo&quot;
        ///	      extensions = &quot;.boo&quot;/&gt;
        ///
        ///  &lt;Mode file       = &quot;Cg-Mode.xshd&quot;
        ///	      name       = &quot;Cg&quot;
        ///	      extensions = &quot;.cg;.cgh;.cgfx&quot;/&gt;
        ///
        ///  &lt;Mode file       = &quot;Coco-Mode.xshd&quot;
        ///	      name       = &quot;Coco&quot;
        ///	      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyntaxModes {
            get {
                return ResourceManager.GetString("SyntaxModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tex_Mode {
            get {
                object obj = ResourceManager.GetObject("Tex_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditorControl {
            get {
                object obj = ResourceManager.GetObject("TextEditorControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VBNET_Mode {
            get {
                object obj = ResourceManager.GetObject("VBNET_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XML_Mode {
            get {
                object obj = ResourceManager.GetObject("XML_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
